### ISSUE TITLE
"sh-elf-gcc: error: unrecognized command line option '-mexword' " when compiling the toolchain

### ISSUE THREAD

**Issue by caesarw** [brijohn/buildscripts#2]
Hello!
Here's my setup:
OS: Arch Linux
Compiler: GCC 9.2.1

```libexword``` is installed.

Terminal Output:
```
Building & installing libdataplus
Building build/_libdataplus...
Building build/_libsh4a...
Building build/_libgraphics...
bcd.c
adc.s
color.c
exp.c
cpg.s
drawing.c
sh-elf-gcc: error: unrecognized command line option '-mexword'
sh-elf-gcc: error: unrecognized command line option '-mexword'
sh-elf-gcc: error: unrecognized command line option '-mexword'
sh-elf-gcc: error: unrecognized command line option '-mexword'
sh-elf-gcc: error: unrecognized command line option '-mexword'
sh-elf-gcc: error: unrecognized command line option '-mexword'
make[1]: *** [/home/username/devkitarm/src/build/devkitSH4/exword_rules:44: bcd.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [/home/username/devkitarm/src/build/devkitSH4/exword_rules:49: adc.o] Error 1
make[1]: *** [/home/username/devkitarm/src/build/devkitSH4/exword_rules:44: color.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [/home/username/devkitarm/src/build/devkitSH4/exword_rules:44: exp.o] Error 1
make[1]: *** [/home/username/devkitarm/src/build/devkitSH4/exword_rules:49: cpg.o] Error 1
make[1]: *** [/home/username/devkitarm/src/build/devkitSH4/exword_rules:44: drawing.o] Error 1
make: *** [target.mk:21: build/_libdataplus] Error 2
make: *** Waiting for unfinished jobs....
make: *** [target.mk:21: build/_libsh4a] Error 2
make: *** [target.mk:21: build/_libgraphics] Error 2
libdataplus build failed
```

Thanks a lot for helping!

**Comment by brijohn** [comment]
Did it properly build and install the gcc compiler first? The -mexword option is added by the dksh4/patches/gcc-8.1.0.patch file. Did that patch apply correctly when building the compiler?

**Comment by caesarw** [comment]
I've patched ```build-devkit.sh``` and ```select_toolchain.sh``` because the download link in the script [https://downloads.devkitpro.org/gcc-8.1.0.tar.xz](https://downloads.devkitpro.org/gcc-8.1.0.tar.xz) returns 404. devkitPro does not provide gcc 8.1.0 anymore. Instead they now provide gcc 9.1.0. I guess that's why the patch wasn't applied.

**Comment by brijohn** [comment]
Yeah that would do it. I've update my repository to use 8.3.0 and supply a patch file for both 8.3.0 and 9.1.0 so you should be able to compile it as is or change the version to 9.1.0 if you would rather use that.

**Comment by caesarw** [comment]
just off-topic, is it possible to run Linux kernel in exword devices? I've seen latest exword devices with WIFI built in.
